---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: registry.gitlab.com/stremio-add-ons/annatar:latest
    ports:
      - "7650:7650"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      BUILD_VERSION: "1.0.0"
      JACKETT_URL: "http://jackett:9117"
      JACKETT_API_KEY: ""
      JACKETT_MAX_RESULTS: "100" # max results from jackett search
      JACKETT_TIMEOUT: "30" # max time spent searching per indexer.
      #JACKETT_INDEXERS: "yts,eztv,kickasstorrents-ws,thepiratebay,therarbg,torrentgalaxy,bitsearch,limetorrents,badasstorrents"
      LISTEN_PORT: "7650"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
