---
version: '3.8'
volumes:
  redis_data: {}
  jackett_config: {}

services:
  annatar:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      # - redis
      - jackett
    environment:
      NUM_WORKERS: "16"
      LOG_LEVEL: debug
      REDIS_URL: "redis://redis:6379/0"
      JACKETT_URL: "http://jackett:9117"
      JACKETT_API_KEY: e5jgcghy3oxbmv5dxm26dl64v0hp1ese 
      JACKETT_INDEXERS: >-
        eztv
        ,kickasstorrents-ws
        ,thepiratebay
        ,therarbg
        ,torrentgalaxy
        ,yts

  redis:
    image: redis:latest
    mem_limit: 4G
    volumes:
      - "redis_data:/data"


  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
