---
version: '3.8'
volumes:
  jackett_config: {}

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    environment:
      NUM_WORKERS: "16"
      LOG_LEVEL: debug
      JACKETT_URL: "http://jackett:9117"
      JACKETT_API_KEY: e5jgcghy3oxbmv5dxm26dl64v0hp1ese 
      JACKETT_INDEXERS: >-
        eztv
        ,kickasstorrents-ws
        ,thepiratebay
        ,therarbg
        ,torrentgalaxy
        ,yts

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
